propose4 = '''
Given an input set of words, partition the words into related categories. Each category must have exactly four words.
And each word must appear in exactly one category. Each line of output should comprise a brief description of the category followed by a colon and the 
four words belonging to that category.

Input:
FINGER, FUR, CLOCK, KNEEL, MAIL, ARROW, HINT, SHELL, NOTES, BOW, DOG, MAPS, STAND, SALUTE, SCALES, DOWN
Output:
ANIMAL COVERINGS: DOWN, FUR, SHELL, SCALES
ACTIONS THAT SHOW RESPECT: BOW, KNEEL, SALUTE, STAND
IPHONE APPS: CLOCK, MAIL, MAPS, NOTES
'POINTERS': ARROW, DOG, FINGER, HINT

Input:
CONVERSE, GAB, VANS, WATER, JORDAN, ANGORA, LEAD, AFGHAN, JABBER, SPEECH, CHAT, ALPACA, BLATHER, TRIAL, YAK, PUMA
Output:
SNEAKER BRANDS: VANS, CONVERSE, JORDAN, PUMA, VANS
LONG-HAIRED ANIMALS: AFGHAN, ALPACA, ANGORA, YAK
PRATTLE ON: BLATHER, CHAT, GAB, JABBER
WORDS THAT CAN PRECEDE 'BALLOON': LEAD, SPEECH, TRIAL, WATER

Input:
PLANKS, BEST, BANKS, CHEERS, LUNGES, DIPS, TAYLOR, WARREN, CARDS, REGARD, YANKS, NATS, MOSS, JAYS, THANKS, SQUATS
Output:
BODYWEIGHT EXERCISES: DIPS, LUNGES, PLANKS, SQUATS
EMAIL SIGN-OFFS: BEST, CHEERS, REGARDS, THANKS
M.L.B. TEAMS, FOR SHORT: CARDS, JAYS, NATS, YANKS
LAST NAMES OF FAMOUS ELIZABETHS: BANKS, MOSS, TAYLOR, WARREN

Input:
DANE, DEER, STEER, MOOSE, BUFFALO, LEAD, LAKE, HOGWASH, NONSENSE, WHITE, GUIDE, FISH, BULL, SEAL, ROT, DIRECT
Output:
BALDERDASH: BULL, HOGWASH, NONSENSE, ROT
HELM: DIRECT, GUIDE, LEAD, STEER
SINGLE/PLURAL ANIMALS: BUFFALO, DEER, FISH, MOOSE
WORDS THAT CAN FOLLOW GREAT: DANE, LAKE, SEAL, WHITE

Input:
UGH, HAI, US, OK, PU, ICK, OUI, EW, DA, WEE, WE, W, JA, SI, WII, O
Output:
INTERJECTIONS OF DISGUST: EW, ICK, PU, UGH
MAGAZINES: O, OK, US, W
"YES" IN DIFFERENT LANGUAGES: HAI, JA, SI, DA
HOMOPHONES: OUI, WE, WEE, WII

Input:
STOCKING, REFEREE, SNOWMAN, MISTLETOE, CROSSWALK, TIGER, CANDY CANE, REINDEER
Output:
THINGS WITH STRIPES: TIGER, CANDY CANE, CROSSWALK, REFEREE
CHRISTMAS-RELATED: SNOWMAN, MISTLETOE, REINDEER, STOCKING

Input:
ALONE, KNOCK, SLAM, PAN, CHOPPED, CATFISH, SURVIVOR, ROAST
Output:
CRITICIZE: KNOCK, PAN, ROAST, SLAM
REALITY SHOWS: ALONE, CATFISH, CHOPPED, SURVIVOR

Input:
BAR, ISLAND, COUNTER, BAG, ATOLL, SPROUT, PACK, DIP, CRAM
Output:
LAND SURROUNDED BY WATER: ATOLL, BAR, ISLAND, KEY
FILL TO EXCESS: CRAM, JAM, PACK, STUFF
WORDS THAT CAN FOLLOW 'BEAN': BAG, COUNTER, DIP, SPROUT

Input:
BALL, SNAKE, SOLE, ARCH, HEEL, DOG, TOE, JERK
Output:
BAD PERSON: DOG, SNAKE, HEEL, JERK
FOOT PARTS: ARCH, BALL, SOLE, TOE

Input:
NOTORIOUS, COTTAGE, DUCK, DODGE, HOBBES, BIRDS, CREAM, ROBIN, SKIRT, STRING, REBECCA, GOOSE, WATSON, ROPE, ESCAPE, SAY
Output:
WORDS THAT CAN PRECEDE 'CHEESE': COTTAGE, CREAM, SAY, STRING
SIDEKICKS: GOOSE, HOBBES, ROBIN, WATSON
AVOID: DODGE, DUCK, ESCAPE, SKIRT

Input:
CAPITAL, IVY, JUSTICE, EQUITY, INTEREST, LITTLE, PREMIER, STOCK
Output:
FINANCIAL TERMS: CAPITAL, EQUITY, INTEREST, STOCK
WORDS THAT CAN PRECEDE 'LEAGUE': IVY, JUSTICE, LITTLE, PREMIER

Input:
{input}
Output:
'''

value_prompt = '''Given a category followed by a colon followed by four words that should match the category, evaluate if the four words fit the proposed category. Output one sentence describing the reason the four words do or do not match the category
followed by a newline followed by sure/maybe/impossible. Use 'sure' conservatively, only when you are 100 percent certain that the four words match the category descriptor.

FLOWERS: DAISY, ROSE, TULIP, VIOLET
A daisy, rose, tulip, and violet are all flowers.
sure

BATHROOM ITEMS: FAMILY, FLUSH, JELLY, WE
Although FLUSH is related to the bathroom it is not an item. FAMILY, WE, and JELLY are not related to bathroom items
impossible

VARIOUS: DUST, LIFE, SPORTS, YELLOW
The category "various" is too vague to know whether these four words are closely related or not
maybe

FARM LIFE: BARN, CHICKEN, FARMER, TRACTOR
A chicken, farmer, tractor and barn could all be found on a farm. These four words are closely related.
sure

THINGS WITH LEAVES: Book, Table, Tea, Tree
Trees have leaves, tea is made from leaves, a table leaf is an insert that can extend the width of the table, and leaf can refer to a page of a book as in "loose leafed pages"
sure

WORDS THAT CAN FOLLOW 'GREAT': DANE, LAKE, SEAL, WHITE
A great dane, great lake, great seal, and great white (shark) are all in-the-language phrases. So each of these words can follow "GREAT". Therefore they are all closely related
sure

B-SOUNDS: BOUQUET, BIRD, RAPPORT, JAMES
The descriptor "B-SOUNDS" is too general to be a proper category. Also RAPPORT and JAMES do not contain a B.
impossible

WORDS THAT CAN PRECEDE PAD: LILY, MOUSE, PAN, MAXI
Although LILY PAD, MOUSE PAD, and MAXI PAD are all in-the-language phrases, PAN PAD is not.
impossible

SINGLE SYLLABLE VERBS: DOG, JERK, SIT, TOE
The category "single syllable verbs" is too general and cannot conclusively determine if these words belong together or not.
maybe

COOKING METHODS: CHOPPED, PAN, ROAST, SLAM
SLAM is not a cooking method
impossible

SINGLE SYLLABLE VERBS: BUZZ, DISH, SCOOP, SKINNY
'SINGLE SYLLABLE VERBS' is too general, so it is unclear whether these four words are closely related or not.
maybe

{input}
'''

nyt = """
NYT Connections 155 - November 13th, 2023
UNIT OF LANGUAGE - LETTER, PARAGRAPH, SENTENCE, WORD
TRADEMARK - FEATURE, HALLMARK, STAMP, TRAIT
FUNNY PERSON - CARD, CLOWN, CUTUP, JOKER
THINGS WITH LEAVES - BOOK, TABLE, TEA, TREE
NYT Connections 154 - November 12th, 2023
PRESIDENTS - FORD, GRANT, LINCOLN, WILSON
SPORTS PROFESSIONALS - COACH, GM, PLAYER, SCOUT
CAR COMPANIES - BMW, HONDA, JAGUAR, SUBARU
COMMON PREFIXES - AUTO, POST, SEMI, SUB
NYT Connections 153 - November 11th, 2023
SPARSE/LACKING - LIGHT, SHORT, SPARE, THIN
FUN TIME - BALL, BLAST, KICK, RIOT
FILMMAKING EQUIPMENT - BOOM, DOLLY, LENS, TRIPOD
“GET A ___!” - CLUE, GRIP, LIFE, ROOM
NYT Connections 152 - November 10th, 2023
SPICES - ANISE, DILL, NUTMEG, SAGE
INTELLIGENT - BRIGHT, QUICK, SHARP, SMART
DEODORANTS - AXE, DEGREE, OLD SPICE, SECRET
MEDIEVAL WEAPONS - CLUB, MACE, SPEAR, SWORD
NYT Connections 151 - November 9th, 2023
DOCTORS’ ORDERS - DIET, EXERCISE, FRESH AIR, SLEEP
EMAIL ACTIONS - COMPOSE, FORWARD, REPLY ALL, SEND
PODCASTS - RADIOLAB, SERIAL, UP FIRST, WTF
___ COMEDY - BLACK, DIVINE, PROP, SKETCH
NYT Connections 150 - November 8th, 2023
BROUGHT TO THE BEACH - FLIP-FLOP, SUNSCREEN, TOWEL, UMBRELLA
TYPES OF FRENCH FRIES - CURLY, SHOESTRING, WAFFLE, WEDGE
EQUIVOCATE - HEDGE, SEE-SAW, WAVER, YO-YO
SECOND WORDS OF VODKA COCKTAILS - BREEZE, MARY, MULE, RUSSIAN
NYT Connections 149 - November 7th, 2023
DIGITAL NOTIFICATION SOUNDS - CHIME, DING, PING, RING
TATTLE - RAT, SING, SNITCH, SQUEAL
GROUP WITHIN A GROUP - CAMP, DIVISION, FACTION, WING
MICROSOFT PRODUCTS - BING, EDGE, SURFACE, WORD
NYT Connections 148 - November 6th, 2023
INVESTMENTS - BOND, CD, OPTION, STOCK
TERMS FOR RECORDS - LP, PLATTER, VINYL, WAX
CUBE-SHAPED - BOUILLON, DIE, ICE, SUGAR
WORDS THAT GO WITH “BONE” - FUNNY, HERRING, SOUP, WISH
NYT Connections 147 - November 5th, 2023
UNCHANGING - EVEN, LEVEL, STABLE, STEADY
LONG, SHARP OBJECTS - LANCE, PIN, SKEWER, SPIT
MUSIC PUBLICATIONS - BILLBOARD, PITCHFORK, ROLLING STONE, SPIN
WORDS WITH NUMERICAL PREFIXES - UNIFORM, BICYCLE, TRILOGY, QUADRANT
NYT Connections 146 - November 4th, 2023
WAYS TO PREPARE - DRILL, PRACTICE, STUDY, TRAIN
HOLLOW CYLINDERS - HOSE, PIPE, STRAW, TUBE
CLUE WEAPONS - CANDLESTICK, KNIFE, ROPE, WRENCH
“E-” THINGS - CIGARETTE, BIKE, TICKET, SPORTS
NYT Connections 145 - November 3rd, 2023
NEVERTHELESS - HOWEVER, STILL, THOUGH, YET
REPEATED WORDS IN EXPRESSIONS - HEAR, KNOCK, THERE, TUT
WORDS ABBREVIATED WITH LETTERS - ARE, SEE, WHY, YOU
ROYAL ___ - FAMILY, FLUSH, JELLY, WE
NYT Connections 144 - November 2nd, 2023
IGNITE - BURN, KINDLE, LIGHT, TORCH
INFORMATION - DATA, INFO, INTEL, NEWS
SMALL WOODED AREA - DELL, GLEN, HOLLOW, VALLEY
THINGS WITH CORES - APPLE, COMPUTER, PLANET, REACTOR
NYT Connections 143 - November 1st, 2023
SOCIAL MEDIA ACTIONS - FOLLOW, LIKE, SHARE, SUBSCRIBE
USE A NEEDLE AND THREAD - DARN, HEM, SEAM, SEW
SHOWS SET IN HOSPITALS - ER, HOUSE, RATCHED, SCRUBS
EXPRESSIONS OF HESITATION - ERM, UH, UM, WELL
NYT Connections 142 - October 31st, 2023
FLOWERS - DAISY, ROSE, TULIP, VIOLET
SEEN ON A FARM - BARN, CHICKEN, FARMER, TRACTOR
HORROR DIRECTORS - ASTER, CARPENTER, CRAVEN, WAN
___ JACKET - DUST, LIFE, SPORTS, YELLOW
NYT Connections 141 - October 30th, 2023
BIRD FEATURES - BEAK, FEATHER, TALON, WING
BLINK OF AN EYE - FLASH, HEARTBEAT, SECOND, WINK
MAHJONG TILES - BAMBOO, DRAGON, SEASON, WIND
___ BUTTON - BELLY, HOT, PANIC, SNOOZE
NYT Connections 140 - October 29th, 2023
MISHMASH - HASH, JUMBLE, MEDLEY, STEW
GO UP AGAINST - CHALLENGE, CONFRONT, FACE, OPPOSE
GROUP OF OFFSPRING - BROOD, CLUTCH, HATCH, LITTER
GUITAR PARTS - BODY, BRIDGE, FRET, NECK
NYT Connections 139 - October 28th, 2023
SENSES - SIGHT, SMELL, TASTE, TOUCH
APPEARANCE - DRESS, LOOK, MANNER, STYLE
“AGREE!” - DITTO, LIKEWISE, SAME, SECOND
___ MOON - BLUE, HARVEST, NEW, SAILOR
"""
